# Generated by Django 6.0 on 2025-12-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('on hold', 'on hold'), ('completed', 'completed')], default='active', max_length=32),
        ),
    ]
